### ISSUE TITLE
Kernel Problem?

### ISSUE THREAD

**Issue by ghost** [infiniband-radar/infiniband-radar-web#10]
igest: sha256:e54383277abcbe3142f8e487c44fe160a8297131ac1767aba7eafa42432900d8
Status: Downloaded newer image for node:10.1.0
 ---> 69deca661740
Step 2/13 : WORKDIR /home/node
 ---> Running in dc3f855e467b
Removing intermediate container dc3f855e467b
 ---> 86852b41e8bc
Step 3/13 : COPY server/package.json server/package-lock.json server/
 ---> a9d8d9ee2456
Step 4/13 : WORKDIR server
 ---> Running in 92729fcd44b1
Removing intermediate container 92729fcd44b1
 ---> 6cff9740b6f4
Step 5/13 : RUN npm install
 ---> Running in 9325d229704f

> dtrace-provider@0.8.6 install /home/node/server/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/home/node/server/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/home/node/server/node_modules/dtrace-provider/build'
added 312 packages in 10.089s

Message from syslogd@rb3t0660 at Sep 11 15:35:02 ...
 kernel:Unrecoverable VSX Unavailable Exception f40 at 1ecb1550

Message from syslogd@rb3t0660 at Sep 11 15:35:02 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [kworker/1:5:759]

Message from syslogd@rb3t0660 at Sep 11 15:35:02 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#2 stuck for 22s! [kworker/2:3:748]

Message from syslogd@rb3t0660 at Sep 11 15:35:22 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#4 stuck for 23s! [daemon_PMLnx:2518]

Message from syslogd@rb3t0660 at Sep 11 15:35:25 ...
 kernel:BUG: workqueue lockup - pool cpus=1 node=0 flags=0x0 nice=0 stuck for 50s!

Message from syslogd@rb3t0660 at Sep 11 15:35:25 ...
 kernel:BUG: workqueue lockup - pool cpus=2 node=0 flags=0x0 nice=0 stuck for 50s!

Message from syslogd@rb3t0660 at Sep 11 15:35:25 ...
 kernel:BUG: workqueue lockup - pool cpus=5 node=0 flags=0x0 nice=0 stuck for 51s!

Message from syslogd@rb3t0660 at Sep 11 15:35:55 ...
 kernel:BUG: workqueue lockup - pool cpus=1 node=0 flags=0x0 nice=0 stuck for 80s!

**Comment by carstenpatzke** [comment]
Unfortunately I have absolutely no idea what went wrong. :(
The message `added 312 packages in 10.089s` seems to indicate that at least the packages were successfully installed.

The web interface (this repository here) don't need direct access to an InfiniBand Fabric, so you can run it on another server or even inside a VM.

**Comment by carstenpatzke** [comment]
@Iskenof Did you make any progress?
If you want we can chat over mail in your native language: carsten.patzke@desy.de

**Comment by carstenpatzke** [comment]
I am not sure if the kernel problems are coming from this repository, maybe its a docker error.

Due to its staleness of this issue I will close it.
Feel free to open it again if you have new information.
