### ISSUE TITLE
Dockerbuild-client hang on ppc64le 

### ISSUE THREAD

**Issue by Iskenof** [infiniband-radar/infiniband-radar-web#7]
docker build --build-arg HTTP_PROXY --build-arg HTTPS_PROXY -t client .
Sending build context to Docker daemon  12.48MB
Step 1/16 : FROM node:alpine as builder
 ---> 8f15a336af43
Step 2/16 : RUN apk add --no-cache git
 ---> Using cache
 ---> 0e00aa625734
Step 3/16 : WORKDIR /app/client/
 ---> Using cache
 ---> 11eaa50fee6c
Step 4/16 : COPY client/package.json client/package-lock.json /app/client/
 ---> Using cache
 ---> 0318cabaa05a
Step 5/16 : COPY .git /app/
 ---> Using cache
 ---> 53711f0047eb
Step 6/16 : RUN cd /app/client && npm set progress=false && npm install
 ---> Using cache
 ---> 7cb6a60bb326
Step 7/16 : COPY common/ /app/common
 ---> Using cache
 ---> 8658fd902724
Step 8/16 : RUN cd /app/common/3dparty/vis && npm install
 ---> Using cache
 ---> e0894b4b8bd5
Step 9/16 : COPY client/ /app/client
 ---> Using cache
 ---> 6428a5617625
Step 10/16 : RUN cd /app/client && npm run build
 ---> Running in e025812f262a

> infiniband-radar-client@2.4.2 build /app/client
> vue-cli-service build

-  Building for production...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:17) UnhandledPromiseRejectionWarning: FetchError: request to https://google-webfonts-helper.herokuapp.com/api/fonts failed, reason: getaddrinfo ENOTFOUND google-webfonts-helper.herokuapp.com
    at ClientRequest.<anonymous> (/app/client/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:209:13)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could not find implementations for the following rules specified in the configuration:
    ter-indent
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

**Comment by carstenpatzke** [comment]
Hey,
for the `ter-indent` I opened up an issue (https://github.com/infiniband-radar/infiniband-radar-web/issues/8).
I think the main problem is the build process of the client when trying to fetch the fonts that the tool is using.
I try to protect the users privacy and that is the reason why I try to fetch the fonts in the build process.

Do you have some kind of firewall?
Try to access this site manually: https://google-webfonts-helper.herokuapp.com/api/fonts

**Comment by Iskenof** [comment]
with the same proxy/user a can download the fonts:

wget https://google-webfonts-helper.herokuapp.com/api/fonts
--2019-09-03 16:56:01--  https://google-webfonts-helper.herokuapp.com/api/fonts
Resolving rb-proxy-de.bosch.com (rb-proxy-de.bosch.com)... 10.4.103.143
Connecting to rb-proxy-de.bosch.com (rb-proxy-de.bosch.com)|10.4.103.143|:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 228452 (223K) [application/json]
Saving to: ‘fonts.1’

100%[===================================================================================================================================================================================================>] 228,452     --.-K/s   in 0.09s

2019-09-03 16:56:02 (2.46 MB/s) - ‘fonts.1’ saved [228452/228452]

**Comment by carstenpatzke** [comment]
I think in this case `ENOTFOUND` is an DNS error. It cannot resolve the host `google-webfonts-helper.herokuapp.com`
Do you have some kind of special DNS that you are using? The container might use another one :/

**Comment by Iskenof** [comment]
I think the proxy makes the DNS resolution.

**Comment by 0blu** [comment]
If you find no solution you could remove these lines here:
https://github.com/infiniband-radar/infiniband-radar-web/blob/master/client/vue.config.js#L29-L33

But I strongly encourage you to figure out what is happening inside the container.

**Comment by carstenpatzke** [comment]
If you find no solution you could remove these lines here:
https://github.com/infiniband-radar/infiniband-radar-web/blob/96fc33ab669b07d4495dbf660c9356fa2f7c2f15/client/vue.config.js#L29-L33

But I strongly encourage you to figure out what is happening inside the container.

**Comment by Iskenof** [comment]
after remove this 5 line it works fine
