### ISSUE TITLE
docker-compose version?

### ISSUE THREAD

**Issue by ghost** [infiniband-radar/infiniband-radar-web#9]
Hello,

i see this error message:

> GATEWAY_CERTS="$PWD/ssl_certs" docker-compose up -d
> Unsupported config option for services service: 'client'
> 

which version of docker-compose is working?

**Comment by carstenpatzke** [comment]
Hey,
I am running docker-compose version `1.21.2`.
According to the [compatibility matrix](https://docs.docker.com/compose/compose-file/compose-versioning/) with version 3 you need at least version `1.13.0`.

**Comment by ghost** [comment]
i use docker-compose --version 
docker-compose 1.2.0

**Comment by carstenpatzke** [comment]
[1.2.0](https://github.com/docker/compose/releases/tag/1.2.0) was released in April of 2015. Its definitely too old.

**Comment by carstenpatzke** [comment]
I hope this issue was solved with a newer docker-compose version.
If not, just comment again.
